apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-debug-ssh
spec:
  runMode:
    debug:
      enabled: true
      replicaSpecs:
        - type: worker
          skipInitContainer: true
          command: ["bash", "/t9k/app/ssh_server.sh"]
  torchrunConfig:
    enabled: true
    maxRestarts: 3
    procPerNode: "4"
    rdzvBackend: c10d
  replicaSpecs:
    - type: worker
      replicas: 1
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              args:
                - torch_mnist_trainingjob.py
                - "--save_path"
                - "model_state_dict.pt"
                - "--log_dir"
                - "log"
                - "--backend"
                - "nccl"
              workingDir: /t9k/mnt/tutorial-examples/job/pytorchtrainingjob/ddp
              image: t9kpublic/pytorch-1.13.0:sdk-0.5.2-ssh
              resources:
                requests:
                  cpu: 4
                  memory: 8Gi
                  nvidia.com/gpu: 4
                limits:
                  cpu: 8
                  memory: 16Gi
                  nvidia.com/gpu: 4
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
                - mountPath: /t9k/host_keys
                  name: ssh-host-key
                  readOnly: true
                - mountPath: /t9k/authorized_keys/ssh-user-public-key
                  name: ssh-user-public-key
                  readOnly: true
                  subPath: ssh-user-public-key
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
            - name: ssh-host-key
              secret:
                defaultMode: 420
                secretName: ssh-host-key
            - name: ssh-user-public-key
              secret:
                defaultMode: 420
                items:
                - key: ssh-publickey
                  path: ssh-user-public-key
                secretName: ssh-user-public-key
