apiVersion: batch.tensorstack.dev/v1beta1
kind: WorkflowTemplate
metadata:
  name: hf-to-ah
spec:
  type: SeqPod
  workspaces:
    - name: t9kConfig
      description: Secret that includes a `t9k-config.yaml`.
    - name: tempStorage
      description: PVC that serves as temporary storage.
  params:
    - name: name
      description: Name of the model or dataset to be downloaded from Hugging Face or ModelScope.
    - name: folder
      description: Path of the folder in Asset Hub where the downloaded model or dataset will be placed.
    - name: token
      description: Hugging Face token used to log in to Hugging Face to download gated model or dataset.
    - name: source
      description: Download source. It should be either 'hf' for Hugging Face or 'modelscope' for ModelScope.
    - name: httpProxy
      description: Optional HTTP and HTTPs proxy.
  seqPod:
    steps:
      - args: []
        command: []
        image: 't9kpublic/hf-to-ah:20240426'
        name: worker
        resources:
          limits:
            cpu: 1
            memory: 16Gi
        script: |-
          #!/bin/bash

          set -e

          if [ -n "$(params.httpProxy)" ]; then
              export http_proxy=$(params.httpProxy)
              export https_proxy=$(params.httpProxy)
              echo "Set HTTP Proxy to $(params.httpProxy)"
          fi

          if [ "$(params.source)" = "hf" ]; then
              if [ -n "$(params.token)" ]; then
                  git config --global credential.helper store
                  huggingface-cli login --token "$(params.token)" --add-to-git-credential
              else
                  echo "Token is empty. Skipping login."
              fi
          fi

          cd $(workspaces.tempStorage.path)

          IFS='/' read -ra parts <<< "$(params.name)"
          dir="${parts[1]}"

          rm -rf $dir

          while true; do
              if [ "$(params.source)" = "hf" ]; then
                  git clone https://huggingface.co/$(params.name)
              elif [ "$(params.source)" = "modelscope" ]; then
                  git clone https://www.modelscope.cn/$(params.name).git
              else
                  echo "Invalid source. Please provide 'hf' or 'modelscope'."
              fi

              if [ $? -eq 0 ]; then
                  echo "Clone successful!"
                  break
              else
                  echo "Clone failed. Retrying..."
                  sleep 1
              fi
          done

          rm -rf $dir/.git

          mkdir /root/.t9k
          ln -s $(workspaces.t9kConfig.path)/.t9kconfig /root/.t9k/t9k-config.yaml
          if ! $(ah ls $(params.folder) > /dev/null 2>&1); then
              ah create $(params.folder)
          fi
          ah create $(params.folder)/$dir
          ah commit $(params.folder)/$dir -a "./$dir/*" -m "add files"

          rm -rf $dir
