apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: pic-mnist
spec:
  default: origin
  transformer:
    minReplicas: 1
    template:
      spec:
        containers:
        - name: user-container
          image: t9kpublic/transformer-example:0.1.0
          resources:
            limits:
              cpu: "500m"
              memory: 500Mi
  releases:
    - name: origin
      predictor:
        minReplicas: 1
        model:
          runtime: t9k-tensorflow-serving
        containersResources:
        - name: user-container
          resources:
            limits:
              cpu: "500m"
              memory: 500Mi
        storage:
          pvc:
            name: tutorial
            subPath: tutorial-examples/deployment/mlservice/transformer/model