apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob
spec:
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/job/pytorchtrainingjob/ddp/log
    image: t9kpublic/tensorflow-2.11.0:cpu-sdk-0.5.2
  torchrunConfig:
    enabled: true
    maxRestarts: 3
    procPerNode: "4"
    rdzvBackend: c10d
  replicaSpecs:
    - type: node
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              args:
                - torch_mnist_trainingjob.py
                - "--save_path"
                - "model_state_dict.pt"
                - "--log_dir"
                - "log"
                - "--backend"
                - "gloo"
                - "--no_cuda"
              workingDir: /t9k/mnt/tutorial-examples/job/pytorchtrainingjob/ddp
              image: t9kpublic/pytorch-1.13.0:sdk-0.5.2
              resources:
                requests:
                  cpu: 16
                  memory: 8Gi
                limits:
                  cpu: 32
                  memory: 16Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
