apiVersion: batch.tensorstack.dev/v1beta1
kind: MPIJob
metadata:
  name: keras-mnist-mpijob
spec:
  mpiConfig:
    home: /usr/local
    mca:
      btl: ^openib
      pml: ob1
    extraArgs:
      - -N
      - "1"
      - --enable-recovery
      - --max-restarts
      - "100"
      - --allow-run-as-root
    script:
      - python
      - keras_mnist_mpijob.py
      - "--log_dir"
      - "log"
      - "--no_cuda"
  ssh:
    sshdPath: /usr/sbin/sshd
  runPolicy:
    cleanUpWorkers: true
  replicaSpecs:
  - type: worker
    replicas: 4
    template:
      spec:
        containers:
          - name: worker
            image: t9kpublic/horovod:sdk-0.5.2
            workingDir: /t9k/mnt/tutorial-examples/job/mpijob/horovod-keras
            resources:
              requests:
                cpu: 2
                memory: 2Gi
              limits:
                cpu: 4
                memory: 4Gi
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: tutorial
  - type: launcher
    replicas: 1
    template: {}