apiVersion: batch.tensorstack.dev/v1beta1
kind: GenericJob
metadata:
  name: keras-mnist-genericjob
spec:
  successRules:
    - { "worker": [0] }
  failureRules:
    - { "worker": [0] }
    - { "worker": [1] }
    - { "worker": [2] }
    - { "worker": [3] }
  service:
    ports:
      - name: http
        port: 2222
  cleanUpPolicy: Unfinished
  replicaSpecs:
    - type: worker
      replicas: 4
      restartPolicy:
        policy: OnFailure
        limit: 100
      template:
        spec:
          containers:
            - name: tensorflow
              command:
                - python
                - job/genericjob/keras-multiworker/keras_mnist_genericjob.py
                - "--log_dir"
                - "job/genericjob/keras-multiworker/log"
              workingDir: /t9k/mnt/tutorial-examples
              env:
                - name: TF_CONFIG
                  value: '{"cluster":{"worker":["$(service.worker[0].host):$(service.port[http])","$(service.worker[1].host):$(service.port[http])","$(service.worker[2].host):$(service.port[http])","$(service.worker[3].host):$(service.port[http])"]},"task":{"type":"$(type)","index":$(rank)}}'
              image: t9kpublic/tensorflow-2.11.0:gpu-sdk-0.5.2
              resources:
                requests:
                  cpu: 1
                  memory: 4Gi
                  nvidia.com/gpu: 1
                limits:
                  cpu: 2
                  memory: 8Gi
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
