FROM t9kpublic/torch-2.1.0-notebook:1.77.1

USER root
WORKDIR /t9k/export

# copy files
COPY . .

# install Python packages, e.g. tiktoken
RUN pip install --no-cache-dir -r ./requirements.txt

# install Debian packages, e.g. iputils-ping
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y iputils-ping && rm -rf /var/lib/apt/lists/*

USER t9kuser
WORKDIR /t9k/mnt
