apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: keras-mnist-mlservice
spec:
  default: test
  releases:
    - name: test
      predictor:
        maxReplicas: 1
        minReplicas: 1
        tensorflow:
          image: registry.tensorstack.cn/t9kmirror/tensorflow-serving:2.6.0
          modelUri: pvc://tutorial/tutorial-examples/deployment/pvc/mlservice-keras/saved_model/
          resources:
            limits:
              cpu: 200m
              memory: 500M
