apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: torch-mnist-mlservice
spec:
  default: test
  releases:
    - name: test
      predictor:
        maxReplicas: 1
        minReplicas: 1
        pytorch:
          image: t9kpublicmirror/pytorch-serve:0.4.2-cpu
          modelUri: pvc://tutorial/tutorial-examples/deployment/pvc/mlservice-torch/
          resources:
            limits:
              cpu: 200m
              memory: 500M
