apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: keras-mnist-mlservice-s3
spec:
  default: test
  releases:
    - name: test
      predictor:
        maxReplicas: 1
        minReplicas: 1
        tensorflow:
          image: t9kpublic/tensorflow-serving:2.6.0
          modelUri: s3://tutorial/keras-mnist/
          resources:
            limits:
              cpu: 1
              memory: 1Gi
        storage:
          s3Storage:
            secretName: s3cfg
