apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-single-aimd
spec:
  replicaSpecs:
    - type: master
      replicas: 1
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              command:
                - python
                - aimd/single-worker/torch_mnist_single_aimd.py
                - "--aimd_host"
                - ""
                - "--api_key"
                - ""
                - "--no_cuda"
              workingDir: /t9k/mnt/tutorial-examples
              image: registry.tensorstack.cn/t9k/pytorch-1.13.0:sdk-0.5.2
              resources:
                requests:
                  cpu: 8.0
                  memory: 2Gi
                limits:
                  cpu: 12.0
                  memory: 4Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
