apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codepack-example
  # namespace is specified in `codepack.yaml` and `namespace` field will not be used
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
