apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-ps
spec:
  runPolicy:
    cleanUpPolicy: Unfinished
    backoffLimit: 20
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/job/pytorchtrainingjob/ps/log
    image: registry.tensorstack.cn/t9k/tensorflow-2.11.0:cpu-sdk-0.5.1
  replicaSpecs:
    - type: master
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - command:
                - python3
                - job/pytorchtrainingjob/ps/torch_mnist_trainingjob_ps.py
                - "--no_cuda"
              workingDir: /t9k/mnt/tutorial-examples
              image: registry.tensorstack.cn/t9k/pytorch-1.13.0:sdk-0.5.1
              name: pytorch
              resources:
                requests:
                  cpu: 8000m
                  memory: 2Gi
                limits:
                  cpu: 16000m
                  memory: 4Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
    - type: worker
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - command:
                - python3
                - job/pytorchtrainingjob/ps/torch_mnist_trainingjob_ps.py
                - "--log_dir"
                - "job/pytorchtrainingjob/ps/log"
                - "--save_path"
                - "job/pytorchtrainingjob/ps/model_state_dict.pt"
                - "--no_cuda"
              workingDir: /t9k/mnt/tutorial-examples
              image: registry.tensorstack.cn/t9k/pytorch-1.13.0:sdk-0.5.1
              name: pytorch
              resources:
                requests:
                  cpu: 2000m
                  memory: 1Gi
                limits:
                  cpu: 4000m
                  memory: 2Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
