apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-ps
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  runPolicy:
    cleanUpPolicy: Unfinished
    backoffLimit: 20
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/job/pytorchtrainingjob/ps/log
    image: t9kpublic/tensorflow-2.11.0:cpu-sdk-0.5.2
  replicaSpecs:
    - type: ps
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - command:
                - python
                - torch_mnist_trainingjob_ps.py
                - "--no_cuda"
              workingDir: /t9k/mnt/tutorial-examples/job/pytorchtrainingjob/ps
              image: t9kpublic/pytorch-1.13.0:sdk-0.5.2
              name: pytorch
              resources:
                requests:
                  cpu: 8
                  memory: 4Gi
                limits:
                  cpu: 16
                  memory: 8Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
    - type: worker
      replicas: 4
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - command:
                - python
                - torch_mnist_trainingjob_ps.py
                - "--save_path"
                - "./model_state_dict.pt"
                - "--log_dir"
                - "log"
                - "--no_cuda"
              workingDir: /t9k/mnt/tutorial-examples/job/pytorchtrainingjob/ps
              image: t9kpublic/pytorch-1.13.0:sdk-0.5.2
              name: pytorch
              resources:
                requests:
                  cpu: 2
                  memory: 2Gi
                limits:
                  cpu: 4
                  memory: 4Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
