apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-ps
spec:
  scheduler:
    t9kScheduler:
      queue:
      priority: 0
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/job/pytorchtrainingjob/ps/log
    image: registry.tensorstack.cn/t9k/tensorflow-2.11.0:cpu-sdk-0.5.2
  replicaSpecs:
    - type: master
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - command:
                - python
                - job/pytorchtrainingjob/ps/torch_mnist_trainingjob_ps.py
              workingDir: /t9k/mnt/tutorial-examples
              image: registry.tensorstack.cn/t9k/pytorch-1.13.0:sdk-0.5.2
              name: pytorch
              resources:
                requests:
                  cpu: 4
                  memory: 4Gi
                  nvidia.com/gpu: 4
                limits:
                  cpu: 8
                  memory: 8Gi
                  nvidia.com/gpu: 4
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
    - type: worker
      replicas: 4
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - command:
                - python
                - job/pytorchtrainingjob/ps/torch_mnist_trainingjob_ps.py
                - "--log_dir"
                - "job/pytorchtrainingjob/ps/log"
                - "--save_path"
                - "job/pytorchtrainingjob/ps/model_state_dict.pt"
              workingDir: /t9k/mnt/tutorial-examples
              image: registry.tensorstack.cn/t9k/pytorch-1.13.0:sdk-0.5.2
              name: pytorch
              resources:
                requests:
                  cpu: 2
                  memory: 2Gi
                limits:
                  cpu: 4
                  memory: 4Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
