apiVersion: batch.tensorstack.dev/v1beta1
kind: TensorFlowTrainingJob
metadata:
  name: keras-mnist-trainingjob
spec:
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/job/tensorflowtrainingjob/multiworker/log
    image: registry.tensorstack.cn/t9k/tensorflow-2.11.0:cpu-sdk-0.5.1
  replicaSpecs:
    - type: worker
      replicas: 4
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: tensorflow
              command:
                - python
                - job/tensorflowtrainingjob/multiworker/keras_mnist_trainingjob.py
                - "--log_dir"
                - "job/tensorflowtrainingjob/multiworker/log"
                - "--no_cuda"
              workingDir: /t9k/mnt/tutorial-examples
              image: registry.tensorstack.cn/t9k/tensorflow-2.11.0:cpu-sdk-0.5.1
              resources:
                requests:
                  cpu: 2000m
                  memory: 2Gi
                limits:
                  cpu: 4000m
                  memory: 4Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
