apiVersion: batch.tensorstack.dev/v1beta1
kind: TensorFlowTrainingJob
metadata:
  name: keras-mnist-trainingjob
spec:
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/job/tensorflowtrainingjob/multiworker/log
    image: t9kpublic/tensorflow-2.11.0:cpu-sdk-0.5.2
  replicaSpecs:
    - type: worker
      replicas: 4
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: tensorflow
              command:
                - python
                - keras_mnist_trainingjob.py
                - "--log_dir"
                - "log"
              workingDir: /t9k/mnt/tutorial-examples/job/tensorflowtrainingjob/multiworker
              image: t9kpublic/tensorflow-2.11.0:gpu-sdk-0.5.2
              resources:
                requests:
                  cpu: 1
                  memory: 4Gi
                  nvidia.com/gpu: 1
                limits:
                  cpu: 2
                  memory: 8Gi
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
