apiVersion: tensorstack.dev/v1beta1
kind: AutoTuneExperiment
metadata:
  name: keras-mnist-autotune
spec:
  maxExecSeconds: 3600
  maxTrialNum: 20
  trialConcurrency: 3
  aimd:
    secret: api-key-aimd
    folder: 
  storage: 100Mi
  searchSpace: |-
    {
      "batch_size": {"_type": "choice", "_value": [16, 32, 64, 128]},
      "learning_rate": {"_type": "choice", "_value": [0.0001, 0.001, 0.01, 0.1]},
      "conv_channels1": {"_type": "choice", "_value": [16, 32, 64, 128]}
    }
  trainingConfig:
    type: tensorflow
    scheduler:
      t9kScheduler:
        queue:
        priority: 0
    tasks:
      - type: worker
        replicas: 4
        template:
          spec:
            securityContext:
              runAsUser: 1000
            containers:
              - name: tensorflow
                command:
                  - python
                  - autotune/hpo-keras/keras_mnist_autotune.py
                workingDir: /t9k/mnt/tutorial-examples
                image: registry.tensorstack.cn/t9k/tensorflow-2.11.0:gpu-sdk-0.5.2
                resources:
                  requests:
                    cpu: 1
                    memory: 4Gi
                    nvidia.com/gpu: 1
                  limits:
                    cpu: 2
                    memory: 8Gi
                    nvidia.com/gpu: 1
                volumeMounts:
                  - mountPath: /t9k/mnt
                    name: data
            volumes:
              - name: data
                persistentVolumeClaim:
                  claimName: tutorial
  tuner:
    builtinTunerName: TPE
    classArgs: |-
      {
        "optimize_mode": "maximize", 
        "constant_liar_type": "min"
      }
