apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-aimd
spec:
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/aimd/job/log
    image: t9kpublic/tensorflow-2.11.0:cpu-sdk-0.5.2
  torchrunConfig:
    enable: true
    maxRestarts: 3
    procPerNode: "4"
    rdzvBackend: c10d  
  replicaSpecs:
    - type: node
      replicas: 1
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              command:
                - python
                - aimd/job/torch_mnist_trainingjob_aimd.py
                - "--aimd_host"
                - ""
                - "--api_key"
                - ""
                - "--log_dir"
                - "aimd/job/log"
                - "--backend"
                - "nccl"
              workingDir: /t9k/mnt/tutorial-examples
              image: t9kpublic/pytorch-1.13.0:sdk-0.5.2
              resources:
                requests:
                  cpu: 4
                  memory: 8Gi
                  nvidia.com/gpu: 4
                limits:
                  cpu: 8
                  memory: 16Gi
                  nvidia.com/gpu: 4
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
