apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-em
spec:
  tensorboardSpec:
    trainingLogFilesets:
      - t9k://pvc/tutorial/tutorial-examples/em/data-parallel-training/log
    image: t9kpublic/tensorflow-2.11.0:cpu-sdk-0.5.2
  torchrunConfig:
    enabled: true
    maxRestarts: 3
    procPerNode: "4"
    rdzvBackend: c10d  
  replicaSpecs:
    - type: node
      replicas: 1
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              args:
                - torch_mnist_trainingjob_em.py
                - "--ais_host"
                - ""
                - "--api_key"
                - ""
                - "--save_path"
                - "model_state_dict.pt"
                - "--log_dir"
                - "log"
                - "--backend"
                - "nccl"
              workingDir: /t9k/mnt/tutorial-examples/em/data-parallel-training
              image: t9kpublic/pytorch-2.0.1:sdk-0.6.0-test
              resources:
                requests:
                  cpu: 4
                  memory: 8Gi
                  nvidia.com/gpu: 4
                limits:
                  cpu: 8
                  memory: 16Gi
                  nvidia.com/gpu: 4
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
