apiVersion: batch.tensorstack.dev/v1beta1
kind: ColossalAIJob
metadata:
  name: colossal-palm
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  ssh:
    authMountPath: /root/.ssh
    sshdPath: /usr/sbin/sshd
  torchConfig:
    procPerWorker: 1
    script:
      - /workspace/ColossalAI/examples/language/palm/train.py
      - "--distplan=colossalai"
      - "--dummy_data=True"
  replicaSpecs:
  - type: launcher
    template:
      spec:
        containers:
        - name: launcher
          image: tsz.io/t9k/colossalai:0.2.5-palm
          workingDir: /workspace
          resources: 
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
  - type: worker
    replicas: 4
    template:
      spec:
        nodeName: sm02
        restartPolicy: OnFailure
        containers:
          - image: tsz.io/t9k/colossalai:0.2.5-palm
            imagePullPolicy: IfNotPresent
            name: worker
            resources:
              limits:
                cpu: 2
                memory: 8Gi
                nvidia.com/gpu: 1
              requests:
                cpu: 1
                memory: 4Gi
                nvidia.com/gpu: 1
