apiVersion: batch.tensorstack.dev/v1beta1
kind: ColossalAIJob
metadata:
  name: colossal-palm
spec:
  torchConfig:
    procPerWorker: 1
    script:
      - train.py
      - "--distplan=colossalai"
      - "--dummy_data=True"
  replicaSpecs:
  - type: launcher
    template:
      spec:
        containers:
        - name: launcher
          image: t9kpublic/colossalai:0.2.5-palm
          workingDir: /workspace/ColossalAI/examples/language/palm
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
  - type: worker
    replicas: 4
    template:
      spec:
        restartPolicy: OnFailure
        containers:
          - name: worker
            image: t9kpublic/colossalai:0.2.5-palm
            resources:
              limits:
                cpu: 4
                memory: 8Gi
                nvidia.com/gpu: "1"
              requests:
                cpu: 2
                memory: 4Gi
                nvidia.com/gpu: "1"
  runPolicy:
    cleanUpWorkers: false
