apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: torch-mnist-mlservice-s3
spec:
  default: test
  releases:
    - name: test
      predictor:
        maxReplicas: 1
        minReplicas: 1
        pytorch:
          image: t9kpublic/pytorch-serve:0.4.2-cpu
          modelUri: s3://tutorial/torch-mnist/
          resources:
            limits:
              cpu: 1
              memory: 1Gi
        storage:
          s3Storage:
            secretName: s3cfg
