apiVersion: batch.tensorstack.dev/v1beta1
kind: WorkflowRun
metadata:
  labels:
    batch.tensorstack.dev/workflowTemplate: build-custom-image
  generateName: build-custom-image-run-
spec:
  params:
    - name: contextPath
      value: ./tutorial-examples/build-custom-image
    - name: dockerfile
      value: Dockerfile
    - name: dstImage
      value: '<HOST>/<REPO>/nanogpt:latest'
    - name: builderImage
      value: 't9kpublic/kaniko-project-executor:latest'
  serviceAccountName: managed-project-sa
  timeout: 1h0m0s
  workflowTemplateRef: build-custom-image
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tutorial
    - name: dockerConfig
      secret:
        secretName: docker-config
