apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-debug
spec:
  runMode:
    debug:
      enable: true
      replicaSpecs:
        - type: worker
          skipInitContainer: true
          command: ["sleep", "inf"]
  replicaSpecs:
    - type: worker
      replicas: 2
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              command:
                - python
                - job/pytorchtrainingjob/ddp/torch_mnist_trainingjob.py
                - "--log_dir"
                - "job/pytorchtrainingjob/ddp/log"
                - "--backend"
                - "nccl"
              workingDir: /t9k/mnt/tutorial-examples
              image: t9kpublic/pytorch-1.13.0:sdk-0.5.2
              resources:
                requests:
                  cpu: 1
                  memory: 2Gi
                  nvidia.com/gpu: 1
                limits:
                  cpu: 2
                  memory: 4Gi
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
