apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: torch-mnist-trainingjob-debug
spec:
  runMode:
    debug:
      enable: true
      replicaSpecs:
        - type: worker
          skipInitContainer: true
          command: ["sleep", "inf"]
  torchrunConfig:
    enable: true
    maxRestarts: 3
    procPerNode: "4"
    rdzvBackend: c10d
  replicaSpecs:
    - type: node
      replicas: 1
      restartPolicy: ExitCode
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              args:
                - job/pytorchtrainingjob/ddp/torch_mnist_trainingjob.py
                - "--log_dir"
                - "job/pytorchtrainingjob/ddp/log"
                - "--backend"
                - "nccl"
              workingDir: /t9k/mnt/tutorial-examples
              image: t9kpublic/pytorch-1.13.0:sdk-0.5.2
              resources:
                requests:
                  cpu: 4
                  memory: 8Gi
                  nvidia.com/gpu: 4
                limits:
                  cpu: 8
                  memory: 16Gi
                  nvidia.com/gpu: 4
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: tutorial
