apiVersion: batch.tensorstack.dev/v1beta1
kind: WorkflowRun
metadata:
  generateName: build-image-run-
spec:
  params:
    - name: contextPath
      value: ./tutorial-examples/build-image/build-image-on-platform
    - name: dockerfile
      value: Dockerfile
    - name: dstImage
      value: '<REGISTRY>/<NAMESPACE>/nanogpt:latest'
    - name: builderImage
      value: 't9kpublic/kaniko-project-executor:debug'
  workflowTemplateRef: build-image
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tutorial
    - name: dockerConfig
      secret:
        secretName: docker-config
