apiVersion: batch.tensorstack.dev/v1beta1
kind: MPIJob
metadata:
  name: torch-mnist-mpijob
spec:
  mca:
    btl: ^openib
    pml: ob1
  mpiHome: /usr/local
  ssh:
    sshdPath: /usr/sbin/sshd
  runPolicy:
    cleanUpWorkers: true
  worker:
    replicas: 4
    processesPerWorker: 1
    processRecovery:
      enable: true
      limit: 100
    cmd:
      - python
      - job/mpijob/horovod-torch/torch_mnist_mpijob.py
      - "--log_dir"
      - "job/mpijob/horovod-torch/log"
      - "--no_cuda"
    template:
      spec:
        containers:
          - name: mpi-worker
            image: registry.tensorstack.cn/t9k/horovod:sdk-0.5.1
            imagePullPolicy: IfNotPresent
            workingDir: /t9k/mnt/tutorial-examples
            resources:
              requests:
                cpu: 4000m
                memory: 2Gi
              limits:
                cpu: 8000m
                memory: 4Gi
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: tutorial
  runPolicy:
    cleanUpWorkers: true
