apiVersion: batch.tensorstack.dev/v1beta1
kind: MPIJob
metadata:
  name: torch-mnist-mpijob
spec:
  scheduler:
    t9kScheduler:
      queue: default
      priority: 50
  mpiConfig:
    home: /usr/local
    mca:
      btl: ^openib
      pml: ob1
    extraArgs:
      - -N
      - "1"
      - --enable-recovery
      - --max-restarts
      - "100"
      - --allow-run-as-root
    script:
      - python
      - torch_mnist_mpijob.py
      - "--log_dir"
      - "log"
  ssh:
    sshdPath: /usr/sbin/sshd
  runPolicy:
    cleanUpWorkers: true
  replicaSpecs:
  - type: worker
    replicas: 4
    template:
      spec:
        containers:
          - name: worker
            image: t9kpublic/horovod:sdk-0.5.2
            workingDir: /t9k/mnt/tutorial-examples/job/mpijob/horovod-torch
            resources:
              requests:
                cpu: 1
                memory: 4Gi
                nvidia.com/gpu: 1
              limits:
                cpu: 2
                memory: 8Gi
                nvidia.com/gpu: 1
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: tutorial
  - type: launcher
    replicas: 1
    template: {}

